#!/bin/bash



TITLE="SSH COMPLIANCE CHECK - $(date +%d/%m/%Y" "%R)"

COUNTER=0



# used the append function, to keep a backlog of all the past compliance checks

echo "$TITLE" >> ~/Desktop/Assignment_1/assignment1.log



# This is to over write the existing error log for a fresh file.

echo "$TITLE" > ~/Desktop/Assignment_1/error.log



## 1

# Ensure SSH root login is disabled

grep -i "^\s*PermitRootLogin\s*no\s*(#|$)" /etc/ssh/sshd_config



if [ $? -ne 0 ]

then

	CHECK_1="1.[FAILED] - Ensure SSH root login is disabled"

	echo "$CHECK_1" >> ~/Desktop/Assignment_1/error.log

	((COUNTER++))

else

	CHECK_1="1.[PASS] - Ensure SSH root login is disabled"

fi



echo "$CHECK_1" >> ~/Desktop/Assignment_1/assignment1.log



## 2

# Ensure SSH empty password disabled.

grep -i "^\s*PermitEmptyPasswords\s*no\s*(#|$)" /etc/ssh/sshd_config



if [ $? -ne 0 ]

then

        CHECK_2="2.[FAILED] - Ensure SSH PermitEmptyPasswords is disabled"

	echo "$CHECK_2" >> ~/Desktop/Assignment_1/error.log

        ((COUNTER++))

else

        CHECK_2="2.[PASS] - Ensure SSH PermitEmptyPasswords is disabled"

fi



echo "$CHECK_2" >> ~/Desktop/Assignment_1/assignment1.log



## 3

# Ensure SSH protocol set to 2.

#PROTOCOL=$(ssh -Q protocol-version localhost)

grep -i "^\s*Protocol\s*2\s*(#|$)" /etc/ssh/sshd_config



if [ $? -ne 0 ]

then

        CHECK_3="3.[FAILED] - Ensure SSH Protocol is set to 2"

	echo "$CHECK_3" >> ~/Desktop/Assignment_1/error.log

        ((COUNTER++))

else

        CHECK_3="3.[PASS] - Ensure SSH Protocol is set to 2"

fi



echo "$CHECK_3" >> ~/Desktop/Assignment_1/assignment1.log



## 4

# Ensure password expiration is 90 days or less.

grep -iE "^\s*PASS_MAX_DAYS\s*(?:\d|[0-8][0-9]|90)\s*(#|$)" /etc/login.defs



if [ $? -ne 0 ]

then

	CHECK_4="4.[FAILED] - Ensure Password Expiry is 90 or less days"

        echo "$CHECK_4" >> ~/Desktop/Assignment_1/error.log

	((COUNTER++))

else

	CHECK_4="4.[PASS] - Ensure Password Expiry is 90 or less days"

fi



echo "$CHECK_4" >> ~/Desktop/Assignment_1/assignment1.log



## 5 

# Ensure system accounts are non login.

LOGIN=$(egrep -v "^\+" /etc/passwd | awk -F: '($1!="root" && $1!="sync" && $1!="shutdown" && $1!="halt" && $3<1000 && $7!="/usr/sbin/nologin" && $7!="/bin/false") {print}')



if [ "$LOGIN" == "" ]

then

	CHECK_5="5.[PASS] - Ensure system accounts are non-login"

else

	CHECK_5="5.[FAILED] - Ensure system accounts are non-login"

        echo "$CHECK_5" >> ~/Desktop/Assignment_1/error.log

	((COUNTER++))

fi



echo "$CHECK_5" >> ~/Desktop/Assignment_1/assignment1.log



if [ $COUNTER == 0 ]

then

	RESULT="$COUNTER/5 Non-Compliance"

	mail -s "$RESULT - $TITLE" slxltester@gmail.com <<< "All Compliance test pass."

else

	RESULT="$COUNTER/5 Non-Compliance"

	echo "($RESULT)" >> ~/Desktop/Assignment_1/error.log

	mail -s "$RESULT - $TITLE" slxltester@gmail.com < ~/Desktop/Assignment_1/error.log

fi



echo "$RESULT" >> ~/Desktop/Assignment_1/assignment1.log

echo " " >> ~/Desktop/Assignment_1/assignment1.log



cat ~/Desktop/Assignment_1/assignment1.log | tail -8 | head -7
